### ISSUE TITLE
Can I know the direction of xyz?

### ISSUE THREAD

**Issue by arthur-qiu** [chalmersgit/SphericalHarmonics#4]
For example,         

<img width="542" alt="image" src="https://user-images.githubusercontent.com/28619658/198965808-9af3aef7-fc2b-4f5e-a730-32af79cade4a.png">

**Comment by chalmersgit** [comment]
Hi, sorry for the late reply, just saw this message now. Are you able to clarify your question, or ask it in a different way?

**Comment by arthur-qiu** [comment]
> Hi, sorry for the late reply, just saw this message now. Are you able to clarify your question, or ask it in a different way?

Spherical Harmonics has a coordinate system (x,y,z). Different codes may use different coordinate systems (x, y, z in different directions). So I want to know which one you use in this repo. Thanks.

**Comment by chalmersgit** [comment]
Z is up, Y is forward. You can see the function getNormalMap(width) which will provide xyz coordinates for each pixel in equirectangular format.
