### ISSUE TITLE
getCoefficientsFromFile() throws error

### ISSUE THREAD

**Issue by anaanook** [chalmersgit/SphericalHarmonics#5]
![env](https://github.com/chalmersgit/SphericalHarmonics/assets/8476492/c2355fd5-85c2-4c66-8362-01d65e36308d)
```sphericalHarmonics.getCoefficientsFromFile("test.png")```

Seems to be straighforward usage but its throwing an error:

```  File "C:\Users\anna\PycharmProjects\pythonProject\sphericalHarmonics.py", line 171, in getCoefficientsFromImage
    sh_basis_matrix = getCoefficientsMatrix(xres, lmax)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\anna\PycharmProjects\pythonProject\sphericalHarmonics.py", line 142, in getCoefficientsMatrix
    latLon = xy2ll(x, y, xres, yres)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\anna\PycharmProjects\pythonProject\sphericalHarmonics.py", line 536, in xy2ll
    return np.asarray([yLocToLat(y, height), xLocToLon(x, width)])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.
```

Thanks for taking a look

**Comment by chalmersgit** [comment]
Hi, I don't get this error so it's a bit hard for me to fix. I did a small update that may fix the problem. I've pushed the changes now. let me know how it goes. I've also included a new sample that you can use: 

python sphericalHarmonics.py ./images/grace-new.exr 2

Please let me know how it goes.
